services:
  - type: web
    name: spidey-bot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node index.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_ID
        scope: pr
      - key: DISCORD_CLIENT_SECRET
        scope: pr
      - key: TOKEN
        scope: pr
      - key: OPENAI_API_KEY
        scope: pr
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        value: spidey123
